Update
TEAM-3PM/CopCheck pull request #60
Opened 2024-10-26 22:47 UTC by MekhiTudor

added deletion for single user and worked on comment controllers.

2024-10-26 23:51 UTC, Mekhi-M requested changes
Please look at the comments I made. If there's reason for the changes I highlighted, please let me know.

2024-10-26 23:51 UTC, Mekhi-M commented on server/models/Content.js
Wait in `Content.js` why did you add user_id into the create method?

I think you might have meant to put it in `Comment.js`.

Please fix this before we merge

2024-10-26 23:51 UTC, Mekhi-M commented on server/controllers/contentController.js
Also, why do we need `.createContent()` in `contentController.js`? Don't we already create every content and correctly associate them with a user report in the `.createFullUserReport()` controller (in `fullUserReportController.js`)?

2024-10-26 23:51 UTC, Mekhi-M commented on server/db/seeds/05_contents.js
This file (`05_contents.js` aka the content seeding) will need to be fixed as well if we don't need the `user_id` in our contents table, since it uses the `Content.create()` method and passes in a `user_id`.

2024-10-26 23:55 UTC, MekhiTudor commented on server/models/Content.js
I added it because when deleting content I didn't have anything to delete it based on what the user created. only the report ID and I couldn't delete the report ID first due to other reference conflicts. so this was the workaround I managed.

2024-10-26 23:56 UTC, MekhiTudor commented on server/controllers/contentController.js
your right here i had a lapse in judgement and saw comments there and assumed they weren't finished, my bad

2024-10-26 23:57 UTC, MekhiTudor commented on server/db/seeds/05_contents.js
im still not sure how we would delete the content when deleting a users account without it.

2024-10-27 02:23 UTC, Mekhi-M approved these changes
thanks for implementing all of this stuff 🫡

2024-10-27 02:23 UTC, merged